language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
    - "sudo apt-get install libxml2 2>&1 | tail -n 4"

install:
    # also include test coverage from Coveralls
    - cpanm --quiet --force --skip-satisfied --notest XML::SAX Bio::Root::Root Devel::Cover::Report::Coveralls

script:
    - PERL5OPT=-MDevel::Cover=+ignore,prove,-coverage,all prove -lr t
    - cover -report coveralls

notifications:
  email: false

# whitelist branches
branches:
  only:
    - master
